site_name: Tensorflow ML

nav:
  - Home: index.md
  - Support: status.md
  - Regression : reg.md
  - Classification : class.md
  - Tutorials: tutorials.md
  - About: about.md

theme: readthedocs

plugins: 
  - mkdocstrings:
      handlers:
        python:
          paths: [tensorflow_ml]  # search packages in the src folder